<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="tika-config.xml" />
    <None Remove="tika-server.jar" />
    <None Remove="tika\tika-config.xml" />
    <None Remove="tika\tika-server.jar" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="tika\tika-config.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="tika\tika-server.jar">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Boilerpipe.Net.Core" Version="1.0.1" />
    <PackageReference Include="drittich.SemanticSlicer" Version="1.4.0" />
    <PackageReference Include="icu.net" Version="3.0.1" />
    <PackageReference Include="Icu4c.Win.Min" Version="59.1.7" />
    <PackageReference Include="OpenSearch.Client" Version="1.8.0" />
  </ItemGroup>

</Project>
